name: Multi-Event pipeline / workflow

on:
  workflow_dispatch:   # Allows manual trigger from GitHub Actions UI

  push:
    branches:
      - master
      - test

  pull_request:
    branches:
      - master
      - test

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Running on master branch
        run: echo "Running on master push"

  on-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Running on pull requests
        run: echo "Running on pull requests"
