name: Multi-Event pipeline / workflow

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test

jobs:

  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Print city
        run: echo "Kolkata"

    

  on-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Running on pull requests
        run: echo "Running on pull requests"
